genessis_task_create_comment:
    path:     /create_comment/{taskId}
    defaults: { _controller: GenessisUserBundle:Comment:createComment }
    requirements:
        _method:  POST

genessis_task_edit_comment:
    path:     /edit_comment/{id}
    defaults: { _controller: GenessisUserBundle:Comment:editComment }

genessis_task_update_comment:
    path:     /update_comment/{id}
    defaults: { _controller: GenessisUserBundle:Comment:updateComment }
    requirements:
        _method:  POST|PUT
        
genessis_task_delete_comment:
    path:     /delete_comment/{id}
    defaults: { _controller: GenessisUserBundle:Comment:deleteComment }
    requirements:
        _method:  POST|DELETE