genessis_task_index:
    path:     /index
    defaults: { _controller: GenessisUserBundle:Task:index }

genessis_task_add:
    path:     /add
    defaults: { _controller: GenessisUserBundle:Task:add }

genessis_task_create:
    path:     /create
    defaults: { _controller: GenessisUserBundle:Task:create }
    requirements:
        _method:  POST

genessis_task_edit:
    path:     /edit/{id}
    defaults: { _controller: GenessisUserBundle:Task:edit }

genessis_task_update:
    path:     /update/{id}
    defaults: { _controller: GenessisUserBundle:Task:update }
    requirements:
        _method:  POST|PUT

genessis_task_view:
    path:     /view/{id}
    defaults: { _controller: GenessisUserBundle:Task:view }

genessis_task_delete:
    path:     /delete/{id}
    defaults: { _controller: GenessisUserBundle:Task:delete }
    requirements:
        _method:  POST|DELETE

# genessis_task_redirect_add:
#     path: /create
#     defaults:
#         _controller: GenessisUserBundle:Task:add
#         path: /add
#         permanent: true

# genessis_task_redirect_edit:
#     path: /update/{id}
#     defaults:
#         _controller: GenessisUserBundle:Task:edit
#         path: /edit/{id}
#         permanent: true