genessis_user_user:
  resource: "@GenessisUserBundle/Resources/config/routes/user.yml"
  prefix: /{_locale}/user

genessis_user_task:
  resource: "@GenessisUserBundle/Resources/config/routes/task.yml"
  prefix: /{_locale}/task

genessis_user_task_comment:
  resource: "@GenessisUserBundle/Resources/config/routes/comment.yml"
  prefix: /{_locale}/task

# AUTHENTICATION

genessis_user_homepage:
    path:     /{_locale}/
    defaults: { _controller: GenessisUserBundle:User:home }

genessis_user_login:
    path:     /{_locale}/login
    defaults: { _controller: GenessisUserBundle:Security:login, _locale: en }

genessis_user_login_check:
    path:     /login_check
    defaults: { _controller: GenessisUserBundle:Security:loginCheck }

genessis_user_logout:
    path:     /logout