genessis_user_user:
  resource: "@GenessisUserBundle/Resources/config/routes/user.yml"
  prefix: /user

genessis_user_task:
  resource: "@GenessisUserBundle/Resources/config/routes/task.yml"
  prefix: /task